version: '3.8'
services:
# litellm:
#    image: ghcr.io/berriai/litellm:main
#    ports:
#      - "4000:4000"
#    environment:
#      - MODEL=ollama/llama2
#      - OLLAMA_BASE_URL=http://host.docker.internal:11434
#    volumes:
#      - ./config.yaml:/app/config.yaml

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: