version: '3.8'
services:
# litellm:
#    image: ghcr.io/berriai/litellm:main
#    ports:
#      - "4000:4000"
#    environment:
#      - MODEL=ollama/llama2
#      - OLLAMA_BASE_URL=http://host.docker.internal:11434
#    volumes:
#      - ./config.yaml:/app/config.yaml

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg17-trixie
    container_name: postgres
    environment:
      POSTGRES_DB: shoppingdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_vector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ollama_data:
  postgres_vector_data: